services:
  chatter-link-mongo:
    container_name: "chatter-link-mongo"
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - app-network
  chatter-link-server:
    image:  chatter-link-server
    container_name: 'chatter-link-server-container'
    ports:
      - '8080:8080'
    links:
        - chatter-link-mongo
    networks:
      - app-network


networks:
  app-network:
    driver: bridge