spring.application.name: blogIn
spring.data.mongodb.uri: mongodb://localhost:27017/blogin

logging.level.org.springframework.security: DEBUG
logging.level.org.springframework.web: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
